### ISSUE TITLE
Update for Python 3

### ISSUE THREAD

**Issue by ichilton** [saltstack-formulas/napalm-install-formula#12]
Hi!

I'm not using this formula directly, but I referred to it and would suggest it should use python3 now.

On Debian (buster) at least, I also had to install python3-setuptools, rustic and cargo for the pip install to succeed.

This is what I ended up with:

```
napalm-deps:
  pkg.installed:
    - pkgs:
      - libffi-dev
      - libssl-dev
      - libxslt1-dev
      - python3-dev
      - python3-pip
      - python3-cffi
      - python3-setuptools
      - rustc
      - cargo

napalm-install:
  pip.installed:
    - name: napalm
    - upgrade: False
    - require:
      - pkg: napalm-deps
```
